// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlcPhUIHu46UJ7Us4VAdUUJce0IVdxkI',
    appId: '1:228708563090:web:f95fbeb19c636993030e4b',
    messagingSenderId: '228708563090',
    projectId: 'pokesearch-1a326',
    authDomain: 'pokesearch-1a326.firebaseapp.com',
    storageBucket: 'pokesearch-1a326.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHi1McXrlGAnMuRDvUc4dmHGP90mK1KlM',
    appId: '1:228708563090:android:4cea7731af5d94fd030e4b',
    messagingSenderId: '228708563090',
    projectId: 'pokesearch-1a326',
    storageBucket: 'pokesearch-1a326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPH7IwfiOg00S48DMM_oEzyWOdfjIxTk',
    appId: '1:228708563090:ios:4fe41a89638cc964030e4b',
    messagingSenderId: '228708563090',
    projectId: 'pokesearch-1a326',
    storageBucket: 'pokesearch-1a326.appspot.com',
    iosClientId: '228708563090-4epqmd16an25hht1hap716nmsdtidth0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokesearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPH7IwfiOg00S48DMM_oEzyWOdfjIxTk',
    appId: '1:228708563090:ios:4fe41a89638cc964030e4b',
    messagingSenderId: '228708563090',
    projectId: 'pokesearch-1a326',
    storageBucket: 'pokesearch-1a326.appspot.com',
    iosClientId: '228708563090-4epqmd16an25hht1hap716nmsdtidth0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokesearch',
  );
}
